name: MkDocs Deploy
on:
  push:
    branches:
      - main

env:
  FUSION_VERSION: 0.4
  FUSION_DEPLOY_TYPE: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Add explicit timeout
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history

      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install setuptools (for mike)
        run: pip install --upgrade setuptools

      - name: Install MkDocs
        run: pip install mkdocs-material==9.5.0

      - name: Install mikef
        run: pip install mike==2.1.3

      - name: Configure FusionDoc Git user
        run: |
          git config user.name fusiondoc
          git config user.email fusiondoc@example.com

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages #--depth=1

      - name: Deploy latest documentation
        if: env.FUSION_DEPLOY_TYPE == 'release'
        run: mike deploy $FUSION_VERSION latest -u -b gh-pages

      - name: Set default version to latest
        if: env.FUSION_DEPLOY_TYPE == 'release'
        run: mike set-default latest -b gh-pages -p

      - name: Deploy developer documentation
        if: env.FUSION_DEPLOY_TYPE == 'dev'
        run: mike deploy $FUSION_VERSION -u -b gh-pages -p
